timeout: 0

/SlightX
  protocol: limine

  kernel_path: boot():/boot/kernel.elf
  kernel_cmdline: quiet

  module_path: boot():/apps/dummy.bin
  module_string: hello from bootloader

  module_path: boot():/apps/dummy.bin
